### PR TITLE
completed the updates for plasm.py

### PR DESCRIPTION
**Pull request by jorels1**
Hi @amakunin, PR ready for review.

### CODE REVIEW

**Comment by amakunin** [comment]
Hi @jorels1, I'm happy to merge and test while performing additional development on my side. Would you mind if I [clean the history](https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history) to remove some test files you've added before merging though?

**Comment by jorels1** [comment]
Sure @amakunin, you can.

**Comment by jorels1** [comment]
@amakunin, please this PR is ready for review.

**Comment by amakunin** [comment]
edits to plasm.py and iplot.py incorporated through https://github.com/malariagen/anospp-analysis/pull/24/commits/53547daafbe4a094f2ea8eb602f45bbb87bc0d72. I will close this PR without merging as it contains excessive data files

**Comment by jorels1** [comment]
Sure, @amakunin, I agree.

**Pull request closed without merging**
