### PR TITLE
Development of initial module structure and QC functions including wrapper script

### PR DESCRIPTION
**Pull request by amakunin**
resolves #1

### CODE REVIEW

**Comment by amakunin** [comment]
Ready for review. Key considerations:
- utils.py holds prep functions for key three input files (samples manifest, dada2 stats, haplotypes) - designed to work with both legacy and new file formats (the latter is still in flux and open for reasonable requests)
- I've tried to focus on minimal sets of columns required for QC: as much data as possible is generated on loading, e.g. for haplotypes only 4 columns are mandatory (sample_id, target, consensus, reads), others (read_fraction, nalleles) are generated from existing ones
- logging is now introduced, but logic-breaking conditions are still tested with `assert` statements (e.g., wrong column names)
- qc.py includes a wrapper script that can be incorporated in the pipeline - suggest creating the same for other steps
- plotting functions were generalised where possible, but without considering later stages plots - we can focus on code deduplication later
- most functions include log message at INFO level specifying what's happening in a function - this substitutes docstrings and allow for better debugging
- several things omitted for now: bokeh/pyplot interactive plotting, test data, testing automation, CI, code linting, packaging for pypi, versioning - suggest focusing on those once key code is ported to the module

**Comment by mariloubodde** [comment]
Code and structure looks good. I have not tried to run it, nor reviewed in fine-grained detail, but will get to this when using it as a template for transforming my own code.

**Review by mariloubodde — APPROVED** [review]

**Review by mariloubodde — APPROVED** [review]
looks good

**Review by mariloubodde — APPROVED** [review]
looks good

**Pull request merged**
